Update testnet.md
burst-apps-team/burst-wiki pull request #31
Opened 2019-06-20 20:38 UTC by shefass

Added Community run public nodes

2019-06-20 22:08 UTC, harryjph requested changes

2019-06-20 22:08 UTC, harry1453 commented on docs/en/testnet.md
> + http://testnet.burstcoin.network:6876/index.html
Please remove indentation

2019-06-21 15:24 UTC, shefass commented
Fixed and added one more link

2019-06-21 23:25 UTC, harryjph approved these changes
Thanks 😄

2019-06-21 23:25 UTC, merged