Nivok patches
burst-apps-team/burst-wiki pull request #52
Opened 2020-05-03 13:54 UTC by Nivok-Spilkommen

2020-05-03 15:10 UTC, jjos2372 commented on docs/en/500k-hf-checklist.md
> +-   Make sure you have a current version of the wallet (2.4.2 or higher, currently released: )
This was for the old fork, so that version is actually the correct one. Please adjust that so I can accept it.

2020-05-03 15:11 UTC, jjos2372 commented on docs/en/testnet.md
> +* [Faucet 2](http://nivbox.co.uk:7777/)
Nice, thanks!

2020-05-03 18:45 UTC, jjos2372 requested changes
Just that small change on the version (check the comments).

2020-05-03 22:25 UTC, Nivok-Spilkommen commented
Fixed that, not sure what happens next.

2020-05-04 01:13 UTC, jjos2372 approved these changes

2020-05-04 01:14 UTC, merged